[package]
name = "doclight-wasm"
version = "0.1.0"
authors = ["Kai Page <kai@quantaly.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
